# =========================================================
# MYSQL DATABASE (PROD)
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=jyoti@2004

# =========================================================
# JPA PROD SETTINGS
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================================================
# CONNECTION POOL (HikariCP)
# =========================================================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# =========================================================
# LOGGING (PROD SAFE)
# =========================================================
logging.level.root=WARN
logging.level.com.app.quantitymeasurement=INFO