# =========================================================
# H2 DATABASE (DEV)
# =========================================================
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================================================
# H2 CONSOLE
# =========================================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================================================
# JPA DEV SETTINGS
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# =========================================================
# LOGGING (DEV - VERBOSE)
# =========================================================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG