server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:file:./data/userservice-db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration: {}

jwt:
  secretKey: 6f3c9c2a9b1d4e8f7a0c5d9e2b1c4f8a7d6e9b0c3a5f7d1e8b9c2a4d6f8e1a3
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
