# =========================================================
# APPLICATION
# =========================================================
spring.application.name=QuantityMeasurementApp
server.port=8080

# Active Profile (dev or prod)
spring.profiles.active=prod

# =========================================================
# JPA COMMON CONFIG
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# LOGGING (COMMON)
# =========================================================
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG

# =========================================================
# SWAGGER / OPENAPI
# =========================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# =========================================================
# OAUTH2 (COMMON)
# =========================================================
spring.config.import=optional:application-secrets.properties
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#===========================================================
# Start With - http://localhost:8080/oauth2/authorization/google
#===========================================================